export const products = [
    {
      discontpersentage: "5",
      name: "Interior Design",
      price: "35,00 ",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://homelineteam.com/images/products/interior-design/full-home-interior.jpg",
    },
    {
      discontpersentage: "5",
      name: "Wardrobe",
      price: "28,000.00",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://homelineteam.com/images/products/interior-design/wardrobe.jpg",
    },
    {
      discontpersentage: "5",
      name: "Kitchen",
      price: "40,000.00",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://homelineteam.com/images/products/interior-design/kitchen.jpg",
    },
    {
      discontpersentage: "5",
      name: "Living Room",
      price: "22,500.00",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://homelineteam.com/images/products/interior-design/living-room.jpg",
    },
    {
      discontpersentage: "5",
      name: "False Celling",
      price: "50,000.00",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://homelineteam.com/images/products/interior-design/false-ceiling.jpg",
    },
    {
      discontpersentage: "5",
      name: "Interior Lighting",
      price: "7,500.00",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://homelineteam.com/images/products/interior-design/interior-lighting.jpg",
    },
    {
      discontpersentage: "5",
      name: "Touch The Clouds (Medium, Rectangular, Gold) Crystal Chandelier",
      price: "6,800.00",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://www.whiteteak.com/media/catalog/product/h/l/hl157-10001_b__4.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
    },
    {
      discontpersentage: "5",
      name: "Weekend Vibes (Gold) Chandelier",
      price: "5,600.00",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://www.whiteteak.com/media/catalog/product/h/l/hl113-10001_21__1.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
    },
    {
      discontpersentage: "5",
      name: "Touch The Clouds (Small, Gold) Round Crystal Chandelier",
      price: "9,200.00",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://www.whiteteak.com/media/catalog/product/h/l/hl79-10002_16_.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
    },
    {
      discontpersentage: "5",
      name: "Summer Days (Gold, 3 Color LED) Chandelier",
      price: "8,400.00",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://www.whiteteak.com/media/catalog/product/h/l/hl225-10002_11_.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
    },
    {
      discontpersentage: "5",
      name: "Never Seen Forever (Large, Gold, Dimmable LED with Remote Control) Chandelier",
      price: "4,300.00",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://www.whiteteak.com/media/catalog/product/h/l/hl170-10005_19_.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
    },
    {
      discontpersentage: "5",
      name: "Touch The Clouds (Medium, Rectangular, Gold) Crystal Chandelier",
      price: "6,800.00",
      delivery: "Free Delivery",
      category: "InteriorDesgin",
      img: "https://www.whiteteak.com/media/catalog/product/h/l/hl157-10001_b__4.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
    },
    {
      discontpersentage: "5",
      name: "Home Sizzler 2 Piece Garden",
      price: "5,000.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/813tzrKnhEL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Home Sizzler 2 Pieces Abstract",
      price: "3,500.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/710sm2Z0HrL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "ARMENIA HAGUE Italian Silk",
      price: "6,200.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/81JMhxmQVZL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Fashion String Polyester",
      price: "7,500.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/81BxuSLkjvL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Fabrilia Floral Net Semi",
      price: "3,200.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/71GB1VL6VwL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Moroccan Motif Eyelet Glace",
      price: "2,800.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/71m2ZxH6JmL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Room Darkening Window Curtain Plain, Black",
      price: "4,000.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/715Yd3-ZbJL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "OMEMONDE Sun Flower Printed Curtains 7 Feet Door ",
      price: "3,500.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/71DyFVhB0tL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Curtains For Door 8 Feet Long",
      price: "3,800.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/817utKzMJQL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "HIPPO Blackout Indoor Roller Blinds in Roman Style",
      price: "7,000.00",
      delivery: "Free Delivery",
      category: "Blinds",
      img: "https://m.media-amazon.com/images/I/71G1Wu98fbL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Premium Waterproof Bamboo Roll-up Blinds for Outdoor",
      price: "6,500.00",
      delivery: "Free Delivery",
      category: "Blinds",
      img: "https://m.media-amazon.com/images/I/51Q5df+YiCL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Exporthub 2 Piece Eyelet Polyester Door Curtain Set - 7ft, Red",
      price: "8,200.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/41J3a9TgxDL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Vintage Floor Lamp",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Mattressess",
      img: "https://tse1.mm.bing.net/th?id=OIP.XuTOn5MM48Xv7TrD1Ejl5QHaE6&pid=Api&P=0&h=180",
    },
    {
      discontpersentage: "5",
      name: "Industrial Floor Lamp",
      price: "7,500.00",
      delivery: "Free Delivery",
      category: "Mattressess",
      img: "https://tse2.mm.bing.net/th?id=OIP.5yZfsKmw6fYFbPjyd58ktgAAAA&pid=Api&P=0&h=180",
    },
    {
      discontpersentage: "5",
      name: "Decorative Vase Set",
      price: "2,000.00",
      delivery: "Free Delivery",
      category: "Mattressess",
      img: "https://tse4.mm.bing.net/th?id=OIP.0D-4JgYfJoiio2hyzexXqQHaF5&pid=Api&P=0&h=180",
    },
    {
      discontpersentage: "5",
      name: "Abstract Wall Art",
      price: "5,500.00",
      delivery: "Free Delivery",
      category: "Wallpapers",
      img: "https://sp.yimg.com/ib/th?id=OPAC.HVUm66L7DInetw474C474&o=5&pid=21.1&w=160&h=105",
    },
    {
      discontpersentage: "5",
      name: "Decorative Mirror",
      price: "3,800.00",
      delivery: "Free Delivery",
      category: "Wallpapers",
      img: "https://sp.yimg.com/ib/th?id=OPAC.WnPOVwd2aY%2bS1Q474C474&o=5&pid=21.1&w=160&h=105",
    },
    {
      discontpersentage: "5",
      name: "Decorative Sculpture",
      price: "6,200.00",
      delivery: "Free Delivery",
      category: "Wallpapers",
      img: "https://m.media-amazon.com/images/I/61Q8avQbW4L._AC_UL480_FMwebp_QL65_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Decorative Candle Holder",
      price: "2,500.00",
      delivery: "Free Delivery",
      category: "Customised sofa",
      img: "https://m.media-amazon.com/images/I/71W5BsTqO9L._AC_UL480_FMwebp_QL65_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Modern Ceiling Light",
      price: "12,000.00",
      delivery: "Free Delivery",
      category: "Customised sofa",
      img: "https://m.media-amazon.com/images/I/71h2KxLMvUL._AC_UL480_FMwebp_QL65_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Classic Ceiling Light",
      price: "10,500.00",
      delivery: "Free Delivery",
      category: "Customised sofa",
      img: "https://m.media-amazon.com/images/I/513gHtGJGhL._AC_UL480_FMwebp_QL65_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Rustic Ceiling Light",
      price: "13,800.00",
      delivery: "Free Delivery",
      category: "Customised sofa",
      img: "https://m.media-amazon.com/images/I/513gHtGJGhL._AC_UL480_FMwebp_QL65_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Vintage Ceiling Light",
      price: "15,200.00",
      delivery: "Free Delivery",
      category: "Furnitures",
      img: "https://m.media-amazon.com/images/S/al-eu-726f4d26-7fdb/c269eb9c-ec49-49f4-adeb-ffda0b3d4dec._CR0,357,1500,786_SX507_QL70_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Industrial Ceiling Light",
      price: "14,000.00",
      delivery: "Free Delivery",
      category: "Furnitures",
      img: "https://m.media-amazon.com/images/I/61rqI7d0CmL._AC_UL480_FMwebp_QL65_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Outdoor Wall Light",
      price: "6,000.00",
      delivery: "Free Delivery",
      category: "Carpets",
      img: "path/to/image36.jpg",
    },
    {
      discontpersentage: "5",
      name: "Outdoor Post Light",
      price: "8,200.00",
      delivery: "Free Delivery",
      category: "Carpets",
      img: "path/to/image37.jpg",
    },
    {
      discontpersentage: "5",
      name: "Outdoor Hanging Lantern",
      price: "9,500.00",
      delivery: "Free Delivery",
      category: "Outdoor Lights",
      img: "https://aax-eu.amazon.in/x/c/JOM0-m7p2edqqyzN8JtTMQsAAAGRcWBARgMAAAH2AQBvbm9fdHhuX2JpZDEgICBvbm9fdHhuX2ltcDEgICDMK3Np/https://www.amazon.in/dp/B08HPJXYBF/?_encoding=UTF8&pd_rd_i=B08HPJXYBF&ref_=sxts_sparkle_sbv&qid=1724184018&pd_rd_w=UdtqJ&content-id=amzn1.sym.df9fe057-524b-4172-ac34-9a1b3c4e647d%3Aamzn1.sym.df9fe057-524b-4172-ac34-9a1b3c4e647d&pf_rd_p=df9fe057-524b-4172-ac34-9a1b3c4e647d&pf_rd_r=E1TF7N2FDJ5QEWCW7T3P&pd_rd_wg=4q7d4&pd_rd_r=7085d254-83b5-4f64-abcd-e2cf5c808f22&pd_rd_plhdr=t",
    },
    {
      discontpersentage: "5",
      name: "Outdoor Path Light",
      price: "5,200.00",
      delivery: "Free Delivery",
      category: "Outdoor Lights",
      img: "path/to/image39.jpg",
    },
    {
      discontpersentage: "5",
      name: "Outdoor Security Light",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Outdoor Lights",
      img: "path/to/image40.jpg",
    },
    {
      discontpersentage: "5",
      name: "Modern Ceiling Fan",
      price: "12,500.00",
      delivery: "Free Delivery",
      category: "Ceiling Fans",
      img: "path/to/image41.jpg",
    },
    {
      discontpersentage: "5",
      name: "Classic Ceiling Fan",
      price: "10,800.00",
      delivery: "Free Delivery",
      category: "Ceiling Fans",
      img: "path/to/image42.jpg",
    },
    {
      discontpersentage: "5",
      name: "Rustic Ceiling Fan",
      price: "13,300.00",
      delivery: "Free Delivery",
      category: "Ceiling Fans",
      img: "path/to/image43.jpg",
    },
    {
      discontpersentage: "5",
      name: "Vintage Ceiling Fan",
      price: "15,500.00",
      delivery: "Free Delivery",
      category: "Ceiling Fans",
      img: "path/to/image44.jpg",
    },
    {
      discontpersentage: "5",
      name: "Industrial Ceiling Fan",
      price: "14,800.00",
      delivery: "Free Delivery",
      category: "Ceiling Fans",
      img: "path/to/image45.jpg",
    },
    {
      discontpersentage: "5",
      name: "Modern Vanity Light",
      price: "8,000.00",
      delivery: "Free Delivery",
      category: "Vanity Lights",
      img: "path/to/image46.jpg",
    },
    {
      discontpersentage: "5",
      name: "Classic Vanity Light",
      price: "7,500.00",
      delivery: "Free Delivery",
      category: "Vanity Lights",
      img: "path/to/image47.jpg",
    },
    {
      discontpersentage: "5",
      name: "Rustic Vanity Light",
      price: "9,200.00",
      delivery: "Free Delivery",
      category: "Vanity Lights",
      img: "path/to/image48.jpg",
    },
    {
      discontpersentage: "5",
      name: "Vintage Vanity Light",
      price: "10,500.00",
      delivery: "Free Delivery",
      category: "Vanity Lights",
      img: "path/to/image49.jpg",
    },
    {
      discontpersentage: "5",
      name: "Industrial Vanity Light",
      price: "8,800.00",
      delivery: "Free Delivery",
      category: "Vanity Lights",
      img: "path/to/image50.jpg",
    },
    {
      discontpersentage: "5",
      name: "Kind To The Mind (Large, Green, Blue) Clear Glass Chandelier",
      price: "35,000.00",
      delivery: "Free Delivery",
      category: "Chandeliers",
      img: "https://www.whiteteak.com/media/catalog/product/h/l/hl215-10002_5_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
    },
    {
      discontpersentage: "5",
      name: "Mixed Emotions (Large, Chrome, Amber, White) Clear Glass Chandelier",
      price: "28,000.00",
      delivery: "Free Delivery",
      category: "Chandeliers",
      img: "https://www.whiteteak.com/media/catalog/product/h/l/hl217-10003_10_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
    },
    {
      discontpersentage: "5",
      name: "Queen's Necklace (Medium, Rose Gold) Crystal Chandelier",
      price: "40,000.00",
      delivery: "Free Delivery",
      category: "Chandeliers",
      img: "https://www.whiteteak.com/media/catalog/product/h/l/hl23-10004_3_1_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
    },
    {
      discontpersentage: "5",
      name: "Watch the Throne (Large, Horizontal, Gold) Crystal Chandelier",
      price: "22,500.00",
      delivery: "Free Delivery",
      category: "Chandeliers",
      img: "https://www.whiteteak.com/media/catalog/product/h/l/hl125-10004_01_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
    },
    {
      discontpersentage: "5",
      name: "Made In Heaven (Large, Green, White) Glass Chandelier",
      price: "50,000.00",
      delivery: "Free Delivery",
      category: "Chandeliers",
      img: "https://www.whiteteak.com/media/catalog/product/h/l/hl125-10003_1_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
    },
    {
      discontpersentage: "5",
      name: "Industrial Iron Pendant",
      price: "7,500.00",
      delivery: "Free Delivery",
      category: "Pendants",
      img: "path/to/image56.jpg",
    },
    {
      discontpersentage: "5",
      name: "Minimalist White Pendant",
      price: "6,800.00",
      delivery: "Free Delivery",
      category: "Pendants",
      img: "path/to/image57.jpg",
    },
    {
      discontpersentage: "5",
      name: "Classic Black Pendant",
      price: "5,600.00",
      delivery: "Free Delivery",
      category: "Pendants",
      img: "path/to/image58.jpg",
    },
    {
      discontpersentage: "5",
      name: "Glass Globe Pendant",
      price: "9,200.00",
      delivery: "Free Delivery",
      category: "Pendants",
      img: "path/to/image59.jpg",
    },
    {
      discontpersentage: "5",
      name: "Bronze Finish Pendant",
      price: "8,400.00",
      delivery: "Free Delivery",
      category: "Pendants",
      img: "path/to/image60.jpg",
    },
    {
      discontpersentage: "5",
      name: "Classic Wall Light",
      price: "4,300.00",
      delivery: "Free Delivery",
      category: "Wall Lights",
      img: "path/to/image61.jpg",
    },
    {
      discontpersentage: "5",
      name: "Modern LED Wall Light",
      price: "5,000.00",
      delivery: "Free Delivery",
      category: "Wall Lights",
      img: "path/to/image62.jpg",
    },
    {
      discontpersentage: "5",
      name: "Rustic Wall Sconce",
      price: "3,500.00",
      delivery: "Free Delivery",
      category: "Wall Lights",
      img: "path/to/image63.jpg",
    },
    {
      discontpersentage: "5",
      name: "Vintage Wall Lamp",
      price: "6,200.00",
      delivery: "Free Delivery",
      category: "Wall Lights",
      img: "path/to/image64.jpg",
    },
    {
      discontpersentage: "5",
      name: "Art Deco Wall Light",
      price: "7,500.00",
      delivery: "Free Delivery",
      category: "Wall Lights",
      img: "path/to/image65.jpg",
    },
    {
      discontpersentage: "5",
      name: "Modern Table Lamp",
      price: "3,200.00",
      delivery: "Free Delivery",
      category: "Table Lamps",
      img: "path/to/image66.jpg",
    },
    {
      discontpersentage: "5",
      name: "Classic Desk Lamp",
      price: "2,800.00",
      delivery: "Free Delivery",
      category: "Table Lamps",
      img: "path/to/image67.jpg",
    },
    {
      discontpersentage: "5",
      name: "Rustic Table Lamp",
      price: "4,000.00",
      delivery: "Free Delivery",
      category: "Table Lamps",
      img: "path/to/image68.jpg",
    },
    {
      discontpersentage: "5",
      name: "Vintage Table Lamp",
      price: "3,500.00",
      delivery: "Free Delivery",
      category: "Table Lamps",
      img: "path/to/image69.jpg",
    },
    {
      discontpersentage: "5",
      name: "Industrial Desk Lamp",
      price: "3,800.00",
      delivery: "Free Delivery",
      category: "Table Lamps",
      img: "path/to/image70.jpg",
    },
    {
      discontpersentage: "5",
      name: "Modern Floor Lamp",
      price: "7,000.00",
      delivery: "Free Delivery",
      category: "Floor Lamps",
      img: "path/to/image71.jpg",
    },
    {
      discontpersentage: "5",
      name: "Classic Floor Lamp",
      price: "6,500.00",
      delivery: "Free Delivery",
      category: "Floor Lamps",
      img: "path/to/image72.jpg",
    },
    {
      discontpersentage: "5",
      name: "Rustic Floor Lamp",
      price: "8,200.00",
      delivery: "Free Delivery",
      category: "Floor Lamps",
      img: "path/to/image73.jpg",
    },
    {
      discontpersentage: "5",
      name: "MECHIP Car USB Atmosphere Ambient Star Light car interior lights LED decorative armrest box car roof full star",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Full Home Interior",
      img: "https://m.media-amazon.com/images/I/71aEqsBKEuL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "TRU Decor Interior Design Moon Lamp. Decorative LED Lamp, Ideal for Bedroom, Profile Wall, Size: 50 cm, Light Colour: Warm White, 15W",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Full Home Interior",
      img: "https://m.media-amazon.com/images/I/617UmYVNpkL._AC_UY218_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Shinmar 3D (96x144inch, White Tree & Square)",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Full Home Interior",
      img: "https://m.media-amazon.com/images/I/61M-OluWJVL._AC_UY218_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Mopnochromatic",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Full Home Interior",
      img: "https://images.livspace-cdn.com/w:600/h:340/q:50/plain/https://d3gq2merok8n5r.cloudfront.net/img/landingpages/full-home-interiors/Edge_New/new-folder-1657193933-8Jkh5/homes-for-every-budget-desktop-1657197190-XYuZj/2-bhk-1657197417-hijyj.jpg",
    },
    //  /////////////////////////////////////////
    {
      discontpersentage: "5",
      name: "MECHIP Car USB Atmosphere Ambient Star Light car interior lights LED decorative armrest box car roof full star",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Interior Design",
      img: "https://m.media-amazon.com/images/I/71aEqsBKEuL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "TRU Decor Interior Design Moon Lamp. Decorative LED Lamp, Ideal for Bedroom, Profile Wall, Size: 50 cm, Light Colour: Warm White, 15W",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Interior Design",
      img: "https://m.media-amazon.com/images/I/617UmYVNpkL._AC_UY218_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Shinmar 3D (96x144inch, White Tree & Square)",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Interior Design",
      img: "https://m.media-amazon.com/images/I/61M-OluWJVL._AC_UY218_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Mopnochromatic",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Interior Design",
      img: "https://images.livspace-cdn.com/w:600/h:340/q:50/plain/https://d3gq2merok8n5r.cloudfront.net/img/landingpages/full-home-interiors/Edge_New/new-folder-1657193933-8Jkh5/homes-for-every-budget-desktop-1657197190-XYuZj/2-bhk-1657197417-hijyj.jpg",
    },

    {
      discontpersentage: "5",
      name: "Amazon Brand - Solimo Medusa Engineered Wood 2 Door Wardrobe",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Wardrobe",
      img: "https://m.media-amazon.com/images/I/81FH5ahAILL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "@home by Nilkamal Engineered Wood Wardrobe (Urban Teak) | 1 Year Warranty (Milford Without Mirror, 4 Door)",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Wardrobe",
      img: "https://m.media-amazon.com/images/I/81I8zEf65DL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Maison & Cuisine® 12 Layer Collapsible Portable Foldable",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Wardrobe",
      img: "https://m.media-amazon.com/images/I/81oqg8O5CVL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "VIKI Wardrobe | Wooden Almirah for Clothes,Door for",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Wardrobe",
      img: "https://m.media-amazon.com/images/I/71qpfIMwZuL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Home Centre Helios Reynan White Multipurpose Engineered Wood Kitchen",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Kitchen",
      img: "https://m.media-amazon.com/images/I/61VxgYs6feL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "12FOR COLLECTION Stainless Steel 3-Tier Countertop Storage Rack For Corners,",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Kitchen",
      img: "https://m.media-amazon.com/images/I/61eX3uIvTwL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "ARRAY Platinum 4 Bar Stainless Steel Folding Towel Hanging Holder Shelf Rack",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Kitchen",
      img: "https://m.media-amazon.com/images/I/61akTHL6xNL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Furniture Cafe Engineered Wood Multipurpose Wall Shelf Floating Shelves Best for",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Kitchen",
      img: "https://m.media-amazon.com/images/I/81Hu7eWgUkL._AC_UL320_.jpg",
    },
  
    {
      discontpersentage: "5",
      name: "",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Living Room",
      img: "https://m.media-amazon.com/images/I/61SYjlLJ7cL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Living Room",
      img: "https://m.media-amazon.com/images/I/619JNqr3UWL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Living Room",
      img: "https://m.media-amazon.com/images/I/41rzfeSGXbL._SX300_SY300_QL70_FMwebp_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Lukzer 6 Layer Engineered",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Living Room",
      img: "https://m.media-amazon.com/images/I/71w5SR8UKhL._AC_UL400_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Anikaa Trixie Engineered Wood Side Table/Bedside",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Living Room",
      img: "",
    },
    {
      discontpersentage: "5",
      name: "MATTERHORN Wooden Coffee Table, Centre Table, Drawing",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Living Room",
      img: "https://m.media-amazon.com/images/I/71-iqOyAb0L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Nasmodo Foam 3D",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "False Ceiling",
      img: "https://m.media-amazon.com/images/I/61Q8gbbTlpL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "GANE-SHART GA Crystal Glass Chandelier Yellow LED Light Ceiling Decoration for",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "False Ceiling",
      img: "https://m.media-amazon.com/images/I/51gheG3IhDL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Mystic Walls MWZ3206 Cream Golden Flowers Design HD 3D Wallpaper for Ceiling[12 ft x 10 ft] / [366 cm x 305 cm]",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "False Ceiling",
      img: "https://m.media-amazon.com/images/I/71W9bt6hU-L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Nasmodo Foam 3D Ceiling Wallpaper for Living Room, Bedroom, Hall, Home Wall",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "False Ceiling",
      img: "https://m.media-amazon.com/images/I/71GDfIf4m8L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "VRCT Vintage Wall Lamp Industrial Black Diamond Metal Cage Retro Living Room Wall Ceiling Lamp",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Interior Lighting",
      img: "https://m.media-amazon.com/images/I/61ZurVFtJAS._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Craftter Half Cylindrical Shape 5 Watts Wall Lamp Fixture,",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Interior Lighting",
      img: "https://m.media-amazon.com/images/I/815bDiooMKL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "ONEST LED Wall Lighting - Exterior Interior Up Down Wall Light - Waterproof IP65 - Home & Office Wall Light Fixture Lamp for Garden, Terrace, Courtyard, Stairs, Garage - Warm White (Round 6 Way 12W",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Interior Lighting",
      img: "https://m.media-amazon.com/images/I/815bDiooMKL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "INTERIOR HANDICRAFT Multi-Colour Light Crystal Chandelier Jhumar Modern",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Interior Lighting",
      img: "https://m.media-amazon.com/images/I/81SjGZo48VL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Mufasa 5 Watts LED Down Light Wall Light Indoor Outdoor Waterproof Lamp Modern Home Lighting Best for Entrance Gate Pillars Boundary Stairs Warm White, Aluminum (Pack of 1)",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Interior Lighting",
      img: "https://m.media-amazon.com/images/I/51f8uR6MWCL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Craftter Premium Sconces Wooden Base Fabric Shade Round Wall Lamp for Home",
      price: "7,800.00",
      delivery: "Free Delivery",
      category: "Interior Lighting",
      img: "https://m.media-amazon.com/images/I/81tBPWvPuPL._AC_UL320_.jpg",
    },
  
    {
      discontpersentage: "5",
      name: "Cloth Fusion Blackout Curtains 7 Feet Long Set of 2 Room",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Curtains",
      img: "https://m.media-amazon.com/images/I/61P6zkDa34L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Story@Home Blackout Curtains 5 feet long 1 Piece",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Curtains",
      img: "https://m.media-amazon.com/images/I/71ign7Zp18L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Curtains for Living Room, 116 x 152 cm, Cyan, 1 Piece, Perfect",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Curtains",
      img: "https://m.media-amazon.com/images/I/51Uze4abHeL._SX300_SY300_QL70_FMwebp_.jpg",
    },
    {
      discontpersentage: "5",
      name: "LaVichitra 2 Piece Premium Door Curtain with Floral Net - 7ft, Yellow",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Curtains",
      img: "https://m.media-amazon.com/images/I/81oseadEMML._AC_UL320_.jpg",
    },
  
    {
      discontpersentage: "5",
      name: "AIRWILL 100% Cotton Solid Pattern Door Curtains Sized,",
      price: "2,500.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/81HUojux-eL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Tranquebar Curtain Co. 100%",
      price: "2,000.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/81c3uG7VkIL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Story@Home Blackout",
      price: "3,000.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/71oBn29kgdL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Story@Home Geometric Opaque Blackout Curtains 7 Feet Long Set Of 2 Poly",
      price: "2,800.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/81KlD2GuDpL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: " Polyester Leaf Print Window Curtain (Grey, 5 FEET -150)",
      price: "3,500.00",
      delivery: "Free Delivery",
      category: "Curtain",
      img: "https://m.media-amazon.com/images/I/91z+7RqBs-L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Deco Window Printed Semi Blackout Roller Blinds for",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Blinds",
      img: "https://m.media-amazon.com/images/I/91tjRWJVtTL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "HIPPO 100% Blackout Roller Blinds for Windows UV",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Blinds",
      img: "https://m.media-amazon.com/images/I/71tzwve2w0L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "ABOUT SPACE Bamboo Curtains - W 5 ft x H 6 ft -",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Blinds",
      img: "https://m.media-amazon.com/images/I/91teuTXOC4L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Indoor Sun Shade Telescopic Roller Blind Sun Shield",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Blinds",
      img: "https://m.media-amazon.com/images/I/71q9P3a3REL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "MSR 116 Polyester Vertical Blinds/Curtains and Shades for Home",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Blinds",
      img: "https://m.media-amazon.com/images/I/41exjQHASJL._SX300_SY300_QL70_FMwebp_.jpg",
    },
    {
      discontpersentage: "5",
      name: "ZEBRA BLINDS Polyester Horizontal Stripes Curtain",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Blinds",
      img: "https://m.media-amazon.com/images/I/61CelyGV60L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Mr.Chickwala Light Filtering & Cooling PVC Exterior ",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Blinds",
      img: "https://m.media-amazon.com/images/I/5189vN3SR9L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Customize Roller Blinds | HIPPO | Roller Blinds for",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Blinds",
      img: "https://m.media-amazon.com/images/I/81j48qtN9ZL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "ABOUT SPACE Bamboo Curtains - W 4 ft x H 6 ft ",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Blinds",
      img: "https://m.media-amazon.com/images/I/91ODp98rl+L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "DDECOR Live beautiful Readymade Curtains for",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Readymade Curtains",
      img: "https://m.media-amazon.com/images/I/61M3oIJG5CL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Swayam 100% Cotton Door Curtain (1PC) 210TC for Bedroom, Living Room -",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Readymade Curtains",
      img: "https://m.media-amazon.com/images/I/71Nqo4TyydL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Swayam 100% Cotton Window Curtain (1PC) 210TC for Bedroom, Living Room -",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Readymade Curtains",
      img: "https://m.media-amazon.com/images/I/71gWH6CVGML._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Swayam 100% Cotton Window Curtain (1PC) 210TC for Bedroom, Living Room -",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Curtains",
      img: "https://m.media-amazon.com/images/I/71gWH6CVGML._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "alemah 5 Feet Multi Striped Cotton Light Filtering Semi",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Curtains",
      img: "https://m.media-amazon.com/images/I/91PwPl4FrLL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "LUKRAIN® Furniture Pure & Genuine U Shape Leather ",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Sofa Set",
      img: "https://m.media-amazon.com/images/I/71hCUDuKwZL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Sleepify - Stylon 8 Seater Fabric RHS L Shape Sofa Set with 1 Centre Table & 2 Puffy (Dark Grey-Light Grey)",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Sofa Set",
      img: "https://m.media-amazon.com/images/I/61rXCPL-sbL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "FURNY Orionoy 3 Seater Fabric Sofa Set - (Dark Blue)",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Sofa Set",
      img: "https://m.media-amazon.com/images/I/71djyA9VS-L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "FURNY Auromax 7 Seater Fabric 3+2+2 Sofa Set",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Sofa Set",
      img: "https://m.media-amazon.com/images/I/61jFCT9cJGL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "TPS Apparel Customized Photo Printed Bed Sheets Photo Printed on Personalized bedsheets and Pillow Covers",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Bed",
      img: "https://m.media-amazon.com/images/I/71+yYMBPWvL._AC_UL320_.jpg",
    },
  
    {
      discontpersentage: "5",
      name: "Stoa Paris Satin Bedsheets for Double Bed - 300TC Premium Bedsheet with 2 Pillow Covers, Luxury Bedding Set, Gift for",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Bed",
      img: "https://m.media-amazon.com/images/I/81SB3fftTkL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Wakefit Bed | King (78 X 72) Engineered Wood Bed with Storage, 1 Year Warranty | ",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Bed",
      img: "https://m.media-amazon.com/images/I/61HcqU1ZFFL._AC_UL320_.jpg",
    },
  
    {
      discontpersentage: "5",
      name: "",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Wallpapers",
      img: "https://m.media-amazon.com/images/I/51DnhkNUbZL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: 'Ambesonne Antique Tapestry, Map of World Global History Stained Paper Oceans Lands Vintage Atlas, Wall Hanging for Bedroom Living Room Dorm Decor, 40" X 60", Cream Green',
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Wallpapers",
      img: "https://m.media-amazon.com/images/I/818ZHkMIS9L._AC_SY450_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Ambesonne City Pittsburgh Tapestry, Rachel Carson Bridge and Reflection on River Landscape Nighttime, Wide Wall Hanging for Bedroom",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Wallpapers",
      img: "https://images-na.ssl-images-amazon.com/images/I/91vWGqyo-hL._AC_UL165_SR165,165_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Ambesonne Night Tapestry, Composition with Dots Night Sky Theme Abstract Style Arrangement Cosmos Concept, Wide Wall Hanging",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Wallpapers",
      img: "",
    },
    {
      discontpersentage: "5",
      name: "Ambesonne World Map Tapestry, Antique Old World Map in Retro Colors Vintage Nostalgic Design Art Print, Wide Wall Hanging",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Customized Wallpapers",
      img: "https://images-na.ssl-images-amazon.com/images/I/91ggxg0yHVL._AC_UL165_SR165,165_.jpg",
    },
    {
      discontpersentage: "5",
      name: 'FunStick Sapphire Blue Fabric Wallpaper Peel and Stick Soft Velvet Fabric Wallpaper Self Adhesive Blue Felt Fabric Contact Paper for Cabinets Shelf Liner Blue Wall Paper for Bedroom Drawer 15.8"x78.8"',
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Imported Wallpapers",
      img: "https://m.media-amazon.com/images/I/61NWkbU35oL._AC_SY450_.jpg",
    },
    {
      discontpersentage: "5",
      name: "MelunMer Blue Peel and Stick Wallpaper Silk Embossed Self Adhesive Removable Wallpaper",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Imported Wallpapers",
      img: "https://images-na.ssl-images-amazon.com/images/I/51lDn68Lx3L._AC_UL232_SR232,232_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Simon&Siff Textured Wallpaper Distressed Concrete Wallpaper Industrial Metallic Wallpaper 17.3inx19.68ft Grey/Gold Non Woven Vintage Wallpaper for Bedroom 3D Embossed Traditional Wallpaper Non-Pasted",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Imported Wallpapers",
      img: "https://m.media-amazon.com/images/I/91D-zHNfWoL._AC_SX425_.jpg",
    },
    {
      discontpersentage: "5",
      name: 'LACHEERY Thick Gold Grey Concrete Wallpaper Peel and Stick Textured Wallpaper Stick and Peel Waterproof Contact Paper for Walls Chic Gray and Gold Wallpaper for Bedroom Bathroom Wall Covers 15.8"x80"',
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Imported Wallpapers",
      img: "https://m.media-amazon.com/images/I/91qga4+5loL._AC_SX425_.jpg",
    },
    {
      discontpersentage: "5",
      name: '12 Pack Sound Proof Foam Panels for Walls 12"x12"x0.4", Self Adhesive Soundproof Wall Panels, High Density Acoustic Foam Panels is Widely Used for Acoustic Treatment In Various Spaces(White)',
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Foam Panels",
      img: "https://m.media-amazon.com/images/I/61K7GSMCmAL._AC_SX425_.jpg",
    },
    {
      discontpersentage: "5",
      name: '12 Pack Sound Proof Foam Panels for Walls 12"x12"x0.4", Self Adhesive Acoustic Foam Panels, High Density Soundproof Wall Panels is Widely Used for Acoustic Treatment In Various Spaces(White)',
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Foam Panels",
      img: "https://m.media-amazon.com/images/I/31Fc0OyarZL._AC_US100_.jpg",
    },
    //  Peps Mattress
    {
      discontpersentage: "5",
      name: "Linenspa",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Peps Mattress",
      img: "https://m.media-amazon.com/images/I/812ymgJoL1L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Sweetnight",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Peps Mattress",
      img: "https://m.media-amazon.com/images/I/71chFl6ziAL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "4.5 Inch Cool Gel Memory Foam Replacement Mattress",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Peps Mattress",
      img: "https://m.media-amazon.com/images/I/61hcRa2Yt-L._AC_UL320_.jpg",
    },
    ////////  Mattresses
    {
      discontpersentage: "5",
      name: "Linenspa",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Mattresses",
      img: "https://m.media-amazon.com/images/I/812ymgJoL1L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Sweetnight",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Mattresses",
      img: "https://m.media-amazon.com/images/I/71chFl6ziAL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "4.5 Inch Cool Gel Memory Foam Replacement Mattress",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Mattresses",
      img: "https://m.media-amazon.com/images/I/61hcRa2Yt-L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Linenspa",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Mattress",
      img: "https://m.media-amazon.com/images/I/812ymgJoL1L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Sweetnight",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Mattress",
      img: "https://m.media-amazon.com/images/I/71chFl6ziAL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "4.5 Inch Cool Gel Memory Foam Replacement Mattress",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Mattress",
      img: "https://m.media-amazon.com/images/I/61hcRa2Yt-L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "CHICOLOGY - RMBF2764 Cordless Roman Shades Cross-Hatched Modern Fabric Cascade Window Blind",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Roman Blinds",
      img: "https://m.media-amazon.com/images/I/81kl8fkXn9L._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: 'CALYX INTERIORS Cordless Bamboo Roman Shade Blind, Light Filtering, 22.5" W x 48" H, Ceylon Light Russet',
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Roman Blinds",
      img: "https://m.media-amazon.com/images/I/81c8PDxBGoL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Madison Park Galen Cordless Roman Shades - Fabric Privacy Single Panel Darkening, Energy Efficient, Thermal",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Roman Blinds",
      img: "https://m.media-amazon.com/images/I/81UtqRSHuTL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "CHICOLOGY",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Zebra Blinds",
      img: "https://m.media-amazon.com/images/I/61Xu1lYSDTL._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: "Persilux",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Zebra Blinds",
      img: "https://m.media-amazon.com/images/I/61yclDT4oML._AC_UL320_.jpg",
    },
    {
      discontpersentage: "5",
      name: 'CALYX INTERIORS Cordless Bamboo Roman Shade Blind, Light Filtering, 22.5" W x 48" H, Ceylon Light Russet',
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Wooden Blinds",
      img: "https://m.media-amazon.com/images/I/81c8PDxBGoL._AC_UL320_.jpg",
    },
    // llllllllllllllllllllllllllllll
    {
      discontpersentage: "5",
      name: "",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Flooring ",
      img: "",
    },
    {
      discontpersentage: "5",
      name: "",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Flooring ",
      img: "",
    },
    //  Flooring  
    {
      discontpersentage: "5",
      name: "TEAK OVER",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Flooring",
      img: "https://s3.amazonaws.com/adroitart/images/22367/original/WL6001_zoom.JPG?1720683176",
    },
    {
      discontpersentage: "5",
      name: "MURPHY BROWN",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Flooring",
      img: "https://s3.amazonaws.com/adroitart/images/22367/original/WL6001_zoom.JPG?1720683176",
    },
    {
      discontpersentage: "5",
      name: "WOODY WALNUT",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Flooring",
      img: "https://s3.amazonaws.com/adroitart/images/22362/large/WL6003_%281%29.JPG?1720683125",
    },
    {
      discontpersentage: "5",
      name: "CARAMEL NUDE",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Flooring",
      img: "https://s3.amazonaws.com/adroitart/images/22360/large/WL6004.JPG?1720683095",
    },
    {
      discontpersentage: "5",
      name: "MAGNETIC MAHOGANY",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Flooring",
      img: "https://s3.amazonaws.com/adroitart/images/22358/large/WL6005.JPG?1720683068",
    },

    //  Wooden Flooring

    {
      discontpersentage: "5",
      name: "TEAK OVER",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Wooden Flooring",
      img: "https://s3.amazonaws.com/adroitart/images/22367/original/WL6001_zoom.JPG?1720683176",
    },
    {
      discontpersentage: "5",
      name: "MURPHY BROWN",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Wooden Flooring",
      img: "https://s3.amazonaws.com/adroitart/images/22367/original/WL6001_zoom.JPG?1720683176",
    },
    {
      discontpersentage: "5",
      name: "WOODY WALNUT",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Wooden Flooring",
      img: "https://s3.amazonaws.com/adroitart/images/22362/large/WL6003_%281%29.JPG?1720683125",
    },
    {
      discontpersentage: "5",
      name: "CARAMEL NUDE",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Wooden Flooring",
      img: "https://s3.amazonaws.com/adroitart/images/22360/large/WL6004.JPG?1720683095",
    },
    {
      discontpersentage: "5",
      name: "MAGNETIC MAHOGANY",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Wooden Flooring",
      img: "https://s3.amazonaws.com/adroitart/images/22358/large/WL6005.JPG?1720683068",
    },
    //  Vinyl Flooring

    
    {
      discontpersentage: "5",
      name: "TEAK OVER",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Vinyl Flooring",
      img: "https://www.shutterstock.com/shutterstock/photos/2491413939/display_1500/stock-photo-batam-indonesia-july-use-of-taco-glue-for-vinyl-adhesive-or-floor-carpet-2491413939.jpg",
    },
    {
      discontpersentage: "5",
      name: "MURPHY BROWN",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Vinyl Flooring",
      img: "https://www.shutterstock.com/shutterstock/photos/1546773929/display_1500/stock-photo-wooden-floor-texture-brown-tiles-floor-background-1546773929.jpg",
    },
    {
      discontpersentage: "5",
      name: "Waterproofness of linoleum.",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Vinyl Flooring",
      img: "https://www.shutterstock.com/shutterstock/photos/2157392863/display_1500/stock-photo-waterproofness-of-linoleum-protection-of-floor-coverings-from-moisture-waterproof-linoleum-in-the-2157392863.jpg",
    },
    {
      discontpersentage: "5",
      name: "wooden stairs and vinyl flooring ",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Vinyl Flooring",
      img: "https://www.shutterstock.com/shutterstock/photos/2356663967/display_1500/stock-photo-wooden-stairs-and-vinyl-flooring-architecture-interior-design-of-contemporary-modern-house-2356663967.jpg",
    },
    {
      discontpersentage: "5",
      name: "closeup of detail leather sofa color",
      price: "9,000.00",
      delivery: "Free Delivery",
      category: "Vinyl Flooring",
      img: "https://www.shutterstock.com/shutterstock/photos/1765805081/display_1500/stock-photo-closeup-of-detail-leather-sofa-color-tone-with-wooden-floor-background-1765805081.jpg",
    },

    
    
  ];